### ISSUE TITLE
Cleaning mocks cache on disable?

### ISSUE THREAD

**Issue by uorbe001** [mfncooper/mockery#16]
Hi,

I've been having issues on my tests using mockery when I try to register mocks. When I register the mocks with the ```useCleanCache``` flag to false my mocks are not being used because some other test is using the module I'm trying to mock, this is expected behaviour as far as I know.  The problem is, I'm using ```useCleanCache``` set to true to avoid this, and that makes my mocked test pass properly, but because some later test is trying to use the same mocked module, my tests fail because the later test gets the mock. I'm calling ```mockery.disable``` and ```mocker.deregisterAll``` after the test where I'm using the mock is finished, but apparently the mock is stored on the node module cache so whenever is required again, I get the mock. Is there a way of forcing the cache to be cleaned after mockery is disabled? I thought that was the default behaviour, but it doesn't seem to be working for me?

Thanks!

**Comment by davglass** [comment]
If you use `useCleanCache`, when `mockery` is disabled the original module cache should be put back in place:
https://github.com/mfncooper/mockery/blob/master/mockery.js#L164-L167

I know it's been a while since this was reported, but if you could add a repro case I could add a test for it to ensure it's doing the right thing.

**Comment by uorbe001** [comment]
tbh, the code where I found this issue is long gone and I can't tell what the problem was anymore, I guess it's safe to just close it unless anyone else can replicate it.
